# Generated by Django 4.2 on 2024-10-01 13:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0007_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'cancelled'), ('requested_refund', 'requested_refund'), ('refund_granted', 'refund_granted'), ('returned', 'returned')], max_length=30)),
                ('order_number', models.CharField(blank=True, max_length=15)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('date_supplied', models.DateField(blank=True, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group_name', models.CharField(choices=[('Antibiotics', 'Antibiotics'), ('Hypertensive_Drugs', 'Hypertensive Drugs'), ('Analgesics', 'Analgesics'), ('Supplements', 'Supplements'), ('Diabetic_Drugs', 'Diabetic Drugs'), ('Cough Syrups', 'Cough Syrups'), ('COPDS', 'COPDS'), ('Medical Lozenges', 'Medical Lozenges'), ('Injectables', 'Injectables'), ('Ashmatic_Drugs', 'Ashmatic Drugs'), ('Antihistamines', 'Antihistamines'), ('Haemanitics', 'Haemanitics'), ('Vital_Signs_Machine', 'Vital Signs Machine'), ('Ulcer_Drugs', 'Ulcer Drugs'), ('Antipsycotics', 'Antipsycotics'), ('Topicals', 'Topicals'), ('Suppositories', 'Suppositories'), ('Ophthalmic Drugs', 'Ophthalmic Drugs'), ('Nasal Drugs', 'Nasal Drugs'), ('Antivirals', 'Antivirals'), ('Anticancer', 'Anticancer'), ('Antilipidemia Drugs', 'Antilipidemia Drugs'), ('Libido_Enhancers', 'Libido Enhancers'), ('Contraceptives', 'Contraceptives'), ('Fertility_Medications', 'Fertility Medications'), ('Sedatives', 'Sedatives'), ('Dressings', 'Dressings'), ('Surgicals', 'Surgicals'), ('Cosmetics', 'Cosmetics'), ('Beverages_and_Drinks', 'Beverages and Drinks'), ('Snacks_and_Biscuits', 'Snacks_and_Biscuits'), ('Toiletry', 'Toiletry')], max_length=30)),
                ('description', models.TextField()),
                ('alt_description', models.CharField(blank=True, editable=False, max_length=150)),
                ('unit', models.CharField(choices=[('Pack', 'Pack'), ('Satchets', 'Satchets'), ('Units', 'Units')], max_length=30)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('stock_level', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('expiration_date', models.DateField()),
                ('manufactured_date', models.DateField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Enter a         valid Nigerian phone number pattern that starts with '0' and 2nd             number either starts with 8, 7, or 9 with additional 9 numbers.", regex='^0[789]\\d{9}$')])),
                ('address', models.CharField(max_length=100)),
                ('companies_sector', models.CharField(choices=[('Pharmaceuticals', 'Pharmaceuticals'), ('Cosmetics', 'Cosmetics'), ('Food_and_Beverages', 'Food and Beverages'), ('Medical_Devices', 'Medical Devices')], max_length=100)),
                ('company_of_the_supplier', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_supplied', models.DateField(blank=True, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_location', models.CharField(max_length=100, verbose_name='location/warehouse')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('stock', models.ManyToManyField(to='inventory.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
