# Generated by Django 4.2 on 2024-10-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_options_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='in_stock',
            field=models.BooleanField(default=False, help_text='Leave this field blank; it will be             automatically generated for you.'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave this field blank; it will be             automatically generated for you.', null=True),
        ),
    ]
