# Generated by Django 4.2 on 2024-10-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_name_alter_stock_in_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Leave this field blank; it will be             automatically generated for you.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Leave this field blank; it will be             automatically generated for you.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Leave this field blank; it will be             automatically generated for you.', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Leave this field blank; it will be             automatically generated for you.', null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='branch_location',
            field=models.CharField(max_length=100, verbose_name='location/Warehouse'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Leave this field blank; it will be             automatically generated for you.', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Leave this field blank; it will be             automatically generated for you.', null=True),
        ),
    ]
