# Generated by Django 4.2 on 2024-10-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_refund_slug_alter_order_slug_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='supplier',
        ),
        migrations.AddField(
            model_name='refund',
            name='customer_full_name',
            field=models.CharField(default='Blaiseooo', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Leave this field blank; it will be             automatically generated for you.', max_length=15),
        ),
    ]
