# Generated by Django 4.2 on 2024-10-04 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_teacherprofile'),
        ('inventory', '0006_rename_order_order_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'cancelled'), ('requested_refund', 'requested_refund'), ('refund_granted', 'refund_granted'), ('returned', 'returned')], max_length=30)),
                ('order_number', models.CharField(blank=True, help_text='Leave this field blank; it will be             automatically generated for you.', max_length=15)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Leave this field blank; it will be             automatically generated for you.', null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ordered', models.BooleanField(default=False, help_text='Tick the checkbox if ordered')),
                ('date_supplied', models.DateField(blank=True, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Leave this field blank; it will be             automatically generated for you.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseorder'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
