# Generated by Django 4.2 on 2024-10-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purchaseorder_orderitem_alter_refund_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='expiration_date',
            field=models.DateField(db_comment='the expiration date of the product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='manufactured_date',
            field=models.DateField(db_comment='the date the stocked product was manufactured'),
        ),
    ]
