# Generated by Django 4.2 on 2024-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
