# Generated by Django 4.2 on 2024-05-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sales_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.FloatField(blank=True, default=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='transaction_id',
            field=models.CharField(blank=True, default=35, help_text='leave it blank, the code will be autogenerated', max_length=15),
            preserve_default=False,
        ),
    ]
