# Generated by Django 4.2 on 2024-05-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(help_text='in US dollars ($)', verbose_name='price'),
        ),
    ]
