# Generated by Django 4.2 on 2024-10-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch_Dinner', 'Lunch & Dinner'), ('Beverages_Drinks', 'Beverages & Drinks')], default='name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('beverages_and_drink', 'Beverages and Drinks'), ('rice', 'Rice Meal'), ('beef_in_stew_sauce', 'Beef In Stew/Sauce'), ('chicken_in_stew_and_sauce', 'Chicken In Stew/Sauce'), ('protein', 'Protein'), ('soups', 'Soups'), ('native_pot', 'Native Pot'), ('pasta_and_noodles', 'Pasta/Noodles'), ('seafood_in_stew_sauce', 'Seafood In Stew/Sauce'), ('swallow', 'Swallow'), ('sides', 'Sides'), ('platter', 'Platter'), ('salad', 'Salad')], default='sub', max_length=30),
            preserve_default=False,
        ),
    ]
